blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/wJGnueZ
    about: This is the support server for all of my projects. Issues should go in this repository, but general support/questions should go here.
  - name: GitHub Discussions page
    url: https://github.com/Makonede/CemuTASTools/discussions
    about: Use the Discussions page for general chat, questions, and TAS show & tell.
