name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your first issue! Contributors like you help us improve. Please wait for your issue to be reviewed.'
        pr-message: 'Thank you for submitting your first pull request! Contributors like you help us improve. Please wait for your pull request to be reviewed.'
